[project]
name = "image_difference_statistics"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "matplotlib",
    "numpy",
    "pillow",
    "ipykernel",
    "scikit-image"
]

[tool.setuptools]
packages = ["image_difference_statistics"]